Master:
  Memory: "512Mi"
  HostName: jenkins2.k8s-engine.jcorioland.io
  ServiceType: ClusterIP 
  InstallPlugins:
      - kubernetes:0.12
      - workflow-aggregator:2.5
      - credentials-binding:1.13
      - git:3.6.0
      - pipeline-github-lib:1.0
      - ghprb:1.39.0
      - blueocean:1.3.3

ScriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
    - "method java.util.Collection toArray"
    - "staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedCall java.lang.Object boolean boolean java.lang.String java.lang.Object[]"
    - "staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedGetProperty java.lang.Object boolean boolean java.lang.Object"

Ingress:
  Annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"

  TLS:
    - secretName: jenkins2.k8s-engine.jcorioland.io
      hosts:
        - jenkins2.k8s-engine.jcorioland.io

Agent:
  Enabled: false